### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by KSLHacks** [great-lakes/botbuilder-wolf#5]
**Description:** Update repository documentation

**Tasks**: 
- [x] Wiki: bootstrap
- [x] Wiki: roadmap
- [ ] Wiki: contributions + conduct
- [ ] Wiki: engineering guidelines
- [x] Main README.md

**Comment by KSLHacks** [comment]
working on main README in `kslhacks/docs` branch
