### ISSUE TITLE
Epic: Slot Data API

### ISSUE THREAD

**Issue by KSLHacks** [great-lakes/botbuilder-wolf#74]
**Description:** Define and implement a set of APIs that allow developers to set/change/update slot data. Wolf should handle this state updates in S1 before proceeding to S2.

**Tasks**: 
- [x] #75 Implement post /api/slotdata [EXAMPLE BOT]
- [x] #77 Save lookup into storage [EXAMPLE BOT]
- [x] #79 Implement slotData processing in S1
- [x] #84 Run all onCompletes
- [x] #80 ~~Cleanup apiStorage~~
- [x] #76 ~~Implement post /api/new-conversation~~

Epic slated for v2 (breaking changes with middleware interface)

**Comment by KSLHacks** [comment]
#76 closed. SlotData API will only support direct line bots. This API endpoint is not needed.
